export const ru = {
  appName: "Рекламный кабинет",
  nav: {
    dashboard: "Дашборд",
    connections: "Подключения",
    syncRuns: "Синхронизации",
    metrics: "Метрики",
    campaigns: "Кампании",
    autopilot: "Автопилот",
    recommendations: "Рекомендации",
    orgs: "Организации",
    members: "Участники",
    audit: "Аудит",
    balance: "Баланс",
    settings: "Настройки",
    plans: "Планы",
    experiments: "Эксперименты",
    login: "Вход",
    signup: "Регистрация",
    home: "Главная",
    team: "Команда"
  },
  actions: {
    login: "Войти",
    logout: "Выйти",
    signup: "Зарегистрироваться",
    create: "Создать",
    save: "Сохранить",
    cancel: "Отмена",
    invite: "Пригласить",
    resend: "Повторить отправку",
    sync: "Запустить синхронизацию",
    runDemo: "Запустить демо-синк",
    refresh: "Обновить",
    check: "Проверить",
    open: "Открыть",
    acceptInvite: "Принять приглашение",
    leave: "Выйти из организации",
    switchOrg: "Сделать активной",
    createOrg: "Создать организацию",
    start: "Запустить",
    back: "Назад",
    close: "Закрыть",
    demoAccess: "Демо-доступ",
    seedDemo: "Создать демо-данные"
  },
  labels: {
    email: "Почта",
    password: "Пароль",
    orgName: "Название организации",
    role: "Роль",
    status: "Статус",
    createdAt: "Создано",
    updatedAt: "Обновлено",
    dateFrom: "Дата начала",
    dateTo: "Дата окончания",
    platform: "Платформа",
    credentials: "Доступы",
    members: "Участники",
    invites: "Приглашения",
    audit: "Журнал",
    connections: "Подключения",
    syncRuns: "Синхронизации",
    metrics: "Метрики",
    search: "Поиск",
    action: "Действие",
    inviteEmail: "Email приглашения",
    inviteRole: "Роль приглашённого",
    inviteExpires: "Срок действия",
    sendStatus: "Статус отправки",
    activeOrg: "Активная организация",
    noData: "Нет данных",
    filters: "Фильтры",
    theme: "Тема",
    themeDark: "Тёмная",
    themeLight: "Светлая",
    orgProfile: "Профиль организации",
    legalType: "Форма",
    legalName: "Юр. наименование",
    inn: "ИНН",
    kpp: "КПП",
    ogrn: "ОГРН",
    ogrnip: "ОГРНИП",
    legalAddress: "Юр. адрес",
    emailForDocs: "Почта для документов",
    phone: "Телефон",
    timezone: "Часовой пояс",
    currency: "Валюта",
    done: "Готово"
  },
  roles: {
    owner: "Владелец",
    admin: "Администратор",
    member: "Участник",
    viewer: "Наблюдатель"
  },
  statuses: {
    queued: "В очереди",
    running: "В процессе",
    success: "Успешно",
    failed: "Ошибка",
    canceled: "Отменено",
    pending: "Ожидает",
    draft: "Черновик",
    active: "Активно",
    paused: "Пауза",
    archived: "Архив"
  },
  inviteStatus: {
    sent: "Отправлено",
    failed: "Ошибка отправки",
    notSent: "Не отправлено"
  },
  messages: {
    loginRequired: "Нужно войти в систему.",
    selectOrg: "Выберите организацию.",
    noConnections: "Подключений пока нет.",
    noInvites: "Приглашений пока нет.",
    noMembers: "Участников пока нет.",
    noAudit: "Событий пока нет.",
    loading: "Загрузка...",
    saved: "Сохранено",
    error: "Ошибка",
    inviteDetected: "Обнаружено приглашение",
    inviteAccepted: "Приглашение принято",
    inviteMismatch: "Приглашение предназначено для другого email",
    syncQueued: "Синхронизация поставлена в очередь",
    syncRunning: "Синхронизация выполняется",
    syncFinished: "Синхронизация завершена",
    noMetrics: "Нет данных за выбранный период",
    demoReady: "Демо-данные подготовлены. Можно войти.",
    loginSuccess: "Вы вошли в систему.",
    signupSuccess: "Регистрация успешна.",
    accountCreated: "Аккаунт создан. Теперь можно войти.",
    homeIntro: "Используйте меню слева, чтобы управлять подключениями, планами и экспериментами.",
    orgProfileSaved: "Профиль организации сохранён"
  },
  pages: {
    dashboardTitle: "KPI-дашборд",
    dashboardSubtitle: "Объединённый график метрик с нормализацией",
    dashboardEmptyTitle: "Нет данных за выбранный период",
    dashboardEmptyDesc: "Запустите синхронизацию или измените фильтры.",
    connectionsSubtitle: "Управляйте подключениями и синхронизациями по рекламным кабинетам.",
    connectionsEmptyDesc: "Создайте подключение и запустите первую синхронизацию.",
    campaignsEmptyTitle: "Кампаний пока нет",
    campaignsEmptyDesc: "Создайте первую кампанию и начните наполнять структуру."
  },
  autopilot: {
    title: "Автопилот рекламы",
    subtitle: "Автоматические рекомендации и черновики улучшений.",
    stateTitle: "Состояние",
    runsTitle: "Последние запуски",
    actionsTitle: "Предложенные действия",
    enabled: "Включён",
    disabled: "Выключен",
    enableButton: "Включить",
    pauseButton: "Пауза",
    interval: "Интервал",
    noRuns: "Запусков пока нет.",
    noActions: "Пока нет предложений.",
    started: "Автопилот запущен",
    paused: "Автопилот выключен",
    resumed: "Автопилот включён"
  }
};
