export const ru = {
  appName: "Рекламный кабинет",
  nav: {
    dashboard: "Дашборд",
    connections: "Подключения",
    syncRuns: "Синхронизации",
    metrics: "Метрики",
    orgs: "Организации",
    members: "Участники",
    audit: "Аудит",
    plans: "Планы",
    experiments: "Эксперименты",
    login: "Вход",
    signup: "Регистрация",
    home: "Главная",
    team: "Команда"
  },
  actions: {
    login: "Войти",
    logout: "Выйти",
    signup: "Зарегистрироваться",
    create: "Создать",
    save: "Сохранить",
    cancel: "Отмена",
    invite: "Пригласить",
    resend: "Повторить отправку",
    sync: "Запустить синхронизацию",
    runDemo: "Запустить демо-синк",
    refresh: "Обновить",
    check: "Проверить",
    open: "Открыть",
    acceptInvite: "Принять приглашение",
    leave: "Выйти из организации",
    switchOrg: "Сделать активной",
    createOrg: "Создать организацию",
    start: "Запустить",
    back: "Назад",
    close: "Закрыть"
  },
  labels: {
    email: "Почта",
    password: "Пароль",
    orgName: "Название организации",
    role: "Роль",
    status: "Статус",
    createdAt: "Создано",
    updatedAt: "Обновлено",
    dateFrom: "Дата начала",
    dateTo: "Дата окончания",
    platform: "Платформа",
    credentials: "Доступы",
    members: "Участники",
    invites: "Приглашения",
    audit: "Журнал",
    connections: "Подключения",
    syncRuns: "Синхронизации",
    metrics: "Метрики",
    search: "Поиск",
    action: "Действие",
    inviteEmail: "Email приглашения",
    inviteRole: "Роль приглашённого",
    inviteExpires: "Срок действия",
    sendStatus: "Статус отправки",
    activeOrg: "Активная организация",
    noData: "Нет данных",
    filters: "Фильтры"
  },
  roles: {
    owner: "Владелец",
    admin: "Администратор",
    member: "Участник",
    viewer: "Наблюдатель"
  },
  statuses: {
    queued: "В очереди",
    running: "В процессе",
    success: "Успешно",
    failed: "Ошибка",
    canceled: "Отменено",
    pending: "Ожидает"
  },
  inviteStatus: {
    sent: "Отправлено",
    failed: "Ошибка отправки",
    notSent: "Не отправлено"
  },
  messages: {
    loginRequired: "Нужно войти в систему.",
    selectOrg: "Выберите организацию.",
    noConnections: "Подключений пока нет.",
    noInvites: "Приглашений пока нет.",
    noMembers: "Участников пока нет.",
    noAudit: "Событий пока нет.",
    loading: "Загрузка...",
    saved: "Сохранено",
    error: "Ошибка",
    inviteDetected: "Обнаружено приглашение",
    inviteAccepted: "Приглашение принято",
    inviteMismatch: "Приглашение предназначено для другого email",
    syncQueued: "Синхронизация поставлена в очередь",
    syncRunning: "Синхронизация выполняется",
    syncFinished: "Синхронизация завершена",
    noMetrics: "Нет данных за выбранный период"
  }
};
