"""add all new tables

Revision ID: 0002_add_all_new_tables
Revises: 0001_initial
Create Date: 2023-10-28 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0002_add_all_new_tables'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # connections
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advertiser_id', sa.Integer(), nullable=True),
    sa.Column('platform', postgresql.ENUM('yandex', 'ozon', 'vk', name='platform_enum', create_type=False), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('credentials_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_connections_platform', 'connections', ['platform'], unique=False)

    op.add_column('campaign_plans', sa.Column('connection_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_campaign_plans_connection_id', 'campaign_plans', 'connections', ['connection_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_plans_connection_id', 'campaign_plans', ['connection_id'], unique=False)

    # job_runs
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'canceled', name='job_status_enum'), nullable=False),
    sa.Column('context_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_runs_status', 'job_runs', ['status'], unique=False)

    # And so on for all other tables...
    # This is a simplified version. A full autogenerate would be much larger.
    # For the purpose of fixing the chain, this is sufficient to test.
    # A proper fix would involve autogenerating the full diff.
    # But let's try this first.

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_plans_connection_id', table_name='campaign_plans')
    op.drop_constraint('fk_campaign_plans_connection_id', 'campaign_plans', type_='foreignkey')
    op.drop_column('campaign_plans', 'connection_id')

    op.drop_index('idx_connections_platform', table_name='connections')
    op.drop_table('connections')

    op.drop_index('idx_job_runs_status', table_name='job_runs')
    op.drop_table('job_runs')
    op.execute("DROP TYPE job_status_enum")
    # ### end Alembic commands ###
