"""add job_runs

Revision ID: 0008_add_job_runs
Revises: 991e7971e174
Create Date: 2023-10-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0008_add_job_runs'
down_revision = '991e7971e174'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='job_status_enum'), nullable=False),
    sa.Column('context_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_runs_created_at_desc', 'job_runs', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_job_runs_job_type', 'job_runs', ['job_type'], unique=False)
    op.create_index('idx_job_runs_status', 'job_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_job_runs_status', table_name='job_runs')
    op.drop_index('idx_job_runs_job_type', table_name='job_runs')
    op.drop_index('idx_job_runs_created_at_desc', table_name='job_runs')
    op.drop_table('job_runs')
    op.execute("DROP TYPE job_status_enum")
    # ### end Alembic commands ###
