"""add connections

Revision ID: 0009_add_connections
Revises: 0008_add_job_runs
Create Date: 2023-10-27 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0009_add_connections'
down_revision = '0008_add_job_runs'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', postgresql.ENUM('yandex', 'ozon', 'vk', name='platform_enum', create_type=False), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('credentials_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_connections_created_at', 'connections', ['created_at'], unique=False)
    op.create_index('idx_connections_platform', 'connections', ['platform'], unique=False)

    op.add_column('campaign_plans', sa.Column('connection_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_campaign_plans_connection_id', 'campaign_plans', 'connections', ['connection_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_plans_connection_id', 'campaign_plans', ['connection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_plans_connection_id', table_name='campaign_plans')
    op.drop_constraint('fk_campaign_plans_connection_id', 'campaign_plans', type_='foreignkey')
    op.drop_column('campaign_plans', 'connection_id')

    op.drop_index('idx_connections_platform', table_name='connections')
    op.drop_index('idx_connections_created_at', table_name='connections')
    op.drop_table('connections')
    # ### end Alembic commands ###
