"""add metric indexes

Revision ID: 0010_add_metric_indexes
Revises: 0009_add_connections
Create Date: 2023-10-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0010_add_metric_indexes'
down_revision = '0009_add_connections'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_metric_snapshots_campaign', 'metric_snapshots', ['campaign_external_id'], unique=False)
    op.create_index('idx_metric_snapshots_experiment_platform_date', 'metric_snapshots', ['experiment_id', 'platform', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_metric_snapshots_experiment_platform_date', table_name='metric_snapshots')
    op.drop_index('idx_metric_snapshots_campaign', table_name='metric_snapshots')
    # ### end Alembic commands ###
