"""add sync_runs

Revision ID: 0011_add_sync_runs
Revises: 0010_add_metric_indexes
Create Date: 2023-10-27 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0011_add_sync_runs'
down_revision = '0010_add_metric_indexes'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('yandex', 'ozon', 'vk', name='platform_enum'), nullable=False),
    sa.Column('run_type', sa.Enum('campaigns', 'metrics', 'full', name='sync_run_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'success', 'failed', 'canceled', name='sync_run_status_enum'), nullable=False),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_runs_experiment_platform_created_at', 'sync_runs', ['experiment_id', 'platform', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_sync_runs_status', 'sync_runs', ['status'], unique=False)

    # Update JobStatus enum if needed (canceled added)
    # Note: altering enum in postgres is tricky via alembic directly without raw sql,
    # but since we are in dev/test flow, we can try to add value if not exists
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE job_status_enum ADD VALUE IF NOT EXISTS 'canceled'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sync_runs_status', table_name='sync_runs')
    op.drop_index('idx_sync_runs_experiment_platform_created_at', table_name='sync_runs')
    op.drop_table('sync_runs')
    op.execute("DROP TYPE sync_run_status_enum")
    op.execute("DROP TYPE sync_run_type_enum")
    # ### end Alembic commands ###
