"""merge heads

Revision ID: 0012_merge_heads
Revises: 991e7971e174, 0011_add_sync_runs
Create Date: 2023-10-28 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0012_merge_heads'
down_revision = ('991e7971e174', '0011_add_sync_runs')
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
