"""sync schema

Revision ID: 991e7971e174
Revises: 0005_experiment_rounds_hyp
Create Date: 2026-01-02 21:53:02.494231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "991e7971e174"
down_revision = "0005_experiment_rounds_hyp"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "advertisers",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("advertisers", "updated_at")

    op.add_column("budget_allocations", sa.Column("experiment_round_id", sa.Integer(), nullable=True))
    op.add_column("budget_allocations", sa.Column("amount", sa.Integer(), nullable=False))
    op.alter_column("budget_allocations", "experiment_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "budget_allocations",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint("uq_budget_allocations_plan_platform_date_creative", "budget_allocations", type_="unique")
    op.drop_constraint("budget_allocations_plan_id_fkey", "budget_allocations", type_="foreignkey")
    op.drop_constraint("budget_allocations_experiment_id_fkey", "budget_allocations", type_="foreignkey")
    op.drop_constraint("budget_allocations_creative_variant_id_fkey", "budget_allocations", type_="foreignkey")
    op.create_foreign_key(None, "budget_allocations", "experiments", ["experiment_id"], ["id"])
    op.create_foreign_key(None, "budget_allocations", "creative_variants", ["creative_variant_id"], ["id"])
    op.create_foreign_key(None, "budget_allocations", "experiment_rounds", ["experiment_round_id"], ["id"])
    op.drop_column("budget_allocations", "date")
    op.drop_column("budget_allocations", "spent_budget")
    op.drop_column("budget_allocations", "allocated_budget")
    op.drop_column("budget_allocations", "plan_id")
    op.drop_column("budget_allocations", "notes")

    op.drop_constraint("campaign_plans_advertiser_id_fkey", "campaign_plans", type_="foreignkey")
    op.create_foreign_key(None, "campaign_plans", "advertisers", ["advertiser_id"], ["id"])

    op.alter_column("connections", "advertiser_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "connections",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint("connections_advertiser_id_fkey", "connections", type_="foreignkey")
    op.create_foreign_key(None, "connections", "advertisers", ["advertiser_id"], ["id"])
    op.drop_column("connections", "updated_at")
    op.drop_column("connections", "notes")

    # --- FIX: reuse existing enum type and create it if needed (checkfirst) ---
    conversion_event_type = postgresql.ENUM(
        "lead",
        "purchase",
        name="conversioneventtype",
        create_type=False,
    )
    conversion_event_type.create(op.get_bind(), checkfirst=True)

    op.add_column("conversion_events", sa.Column("event_id", sa.String(length=36), nullable=False))
    op.add_column("conversion_events", sa.Column("event_type", conversion_event_type, nullable=False))
    op.add_column("conversion_events", sa.Column("occurred_at", sa.DateTime(), nullable=False))
    op.add_column("conversion_events", sa.Column("landing_url", sa.String(length=2048), nullable=False))
    op.add_column("conversion_events", sa.Column("utm_source", sa.String(length=255), nullable=True))
    op.add_column("conversion_events", sa.Column("utm_medium", sa.String(length=255), nullable=True))
    op.add_column("conversion_events", sa.Column("utm_campaign", sa.String(length=255), nullable=True))
    op.add_column("conversion_events", sa.Column("utm_content", sa.String(length=255), nullable=True))
    op.add_column("conversion_events", sa.Column("utm_term", sa.String(length=255), nullable=True))
    op.add_column("conversion_events", sa.Column("contact_phone", sa.String(length=64), nullable=True))
    op.add_column("conversion_events", sa.Column("contact_email", sa.String(length=255), nullable=True))
    op.alter_column(
        "conversion_events",
        "value",
        existing_type=sa.NUMERIC(precision=14, scale=2),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column("conversion_events", "plan_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "conversion_events",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_unique_constraint(None, "conversion_events", ["event_id"])
    op.drop_constraint("conversion_events_experiment_id_fkey", "conversion_events", type_="foreignkey")
    op.drop_constraint("conversion_events_plan_id_fkey", "conversion_events", type_="foreignkey")
    op.create_foreign_key(None, "conversion_events", "experiments", ["experiment_id"], ["id"])
    op.create_foreign_key(None, "conversion_events", "campaign_plans", ["plan_id"], ["id"])
    op.drop_column("conversion_events", "type")
    op.drop_column("conversion_events", "meta_json")

    op.add_column(
        "creative_variants",
        sa.Column("platform", sa.Enum("yandex", "ozon", "vk", name="platform_enum"), nullable=False),
    )
    op.add_column("creative_variants", sa.Column("text", sa.Text(), nullable=True))
    op.add_column("creative_variants", sa.Column("title", sa.String(length=255), nullable=True))
    op.add_column("creative_variants", sa.Column("image_url", sa.String(length=2048), nullable=True))
    op.add_column("creative_variants", sa.Column("media_url", sa.String(length=2048), nullable=True))
    op.add_column("creative_variants", sa.Column("meta_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("creative_variants", sa.Column("moderation_status", sa.String(length=64), nullable=True))
    op.add_column("creative_variants", sa.Column("external_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column(
        "creative_variants",
        "compliance_token",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "creative_variants",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("ix_creative_variants_compliance_token", table_name="creative_variants")
    op.drop_constraint(
        "fk_creative_variants_experiment_round_id_experiment_rounds",
        "creative_variants",
        type_="foreignkey",
    )
    op.drop_constraint("creative_variants_experiment_id_fkey", "creative_variants", type_="foreignkey")
    op.drop_constraint("fk_creative_variants_hypothesis_id_hypotheses", "creative_variants", type_="foreignkey")
    op.create_foreign_key(None, "creative_variants", "hypotheses", ["hypothesis_id"], ["id"])
    op.create_foreign_key(None, "creative_variants", "experiments", ["experiment_id"], ["id"])
    op.drop_column("creative_variants", "experiment_round_id")
    op.drop_column("creative_variants", "updated_at")
    op.drop_column("creative_variants", "payload_json")
    op.drop_column("creative_variants", "status")
    op.drop_column("creative_variants", "external_creative_id")
    op.drop_column("creative_variants", "name")

    op.add_column("experiment_rounds", sa.Column("round_index", sa.Integer(), nullable=False))
    op.add_column("experiment_rounds", sa.Column("budget_plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column("experiment_rounds", sa.Column("started_at", sa.DateTime(), nullable=True))
    op.add_column("experiment_rounds", sa.Column("ended_at", sa.DateTime(), nullable=True))
    op.alter_column(
        "experiment_rounds",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_unique_constraint("uq_round_index", "experiment_rounds", ["experiment_id", "round_index"])
    op.drop_constraint("experiment_rounds_experiment_id_fkey", "experiment_rounds", type_="foreignkey")
    op.create_foreign_key(None, "experiment_rounds", "experiments", ["experiment_id"], ["id"])
    op.drop_column("experiment_rounds", "end_date")
    op.drop_column("experiment_rounds", "updated_at")
    op.drop_column("experiment_rounds", "start_date")
    op.drop_column("experiment_rounds", "metrics_json")
    op.drop_column("experiment_rounds", "status")
    op.drop_column("experiment_rounds", "notes")
    op.drop_column("experiment_rounds", "name")

    op.add_column("experiments", sa.Column("total_budget", sa.Integer(), nullable=True))
    op.add_column("experiments", sa.Column("platforms", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("experiments", sa.Column("processing", sa.Boolean(), nullable=False))
    op.add_column("experiments", sa.Column("start_at", sa.DateTime(), nullable=True))
    op.add_column("experiments", sa.Column("end_at", sa.DateTime(), nullable=True))
    op.add_column("experiments", sa.Column("started_at", sa.DateTime(), nullable=True))
    op.add_column("experiments", sa.Column("ended_at", sa.DateTime(), nullable=True))
    op.alter_column("experiments", "plan_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "experiments",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint("experiments_plan_id_fkey", "experiments", type_="foreignkey")
    op.drop_constraint("fk_experiments_project_id_projects", "experiments", type_="foreignkey")
    op.create_foreign_key(None, "experiments", "campaign_plans", ["plan_id"], ["id"])
    op.create_foreign_key(None, "experiments", "projects", ["project_id"], ["id"])
    op.drop_column("experiments", "updated_at")
    op.drop_column("experiments", "name")
    op.drop_column("experiments", "settings_json")

    op.add_column("hypotheses", sa.Column("text", sa.Text(), nullable=False))
    op.add_column("hypotheses", sa.Column("segmentation_params", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column(
        "hypotheses",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint("hypotheses_experiment_round_id_fkey", "hypotheses", type_="foreignkey")
    op.create_foreign_key(None, "hypotheses", "experiment_rounds", ["experiment_round_id"], ["id"])
    op.drop_column("hypotheses", "updated_at")
    op.drop_column("hypotheses", "metrics_json")
    op.drop_column("hypotheses", "description")
    op.drop_column("hypotheses", "expected_impact")
    op.drop_column("hypotheses", "title")
    op.drop_column("hypotheses", "assumptions_json")

    op.add_column("metric_snapshots", sa.Column("date", sa.Date(), nullable=False))
    op.add_column(
        "metric_snapshots",
        sa.Column("platform", sa.Enum("yandex", "ozon", "vk", name="platform_enum"), nullable=False),
    )
    op.add_column("metric_snapshots", sa.Column("campaign_external_id", sa.String(length=255), nullable=False))
    op.add_column("metric_snapshots", sa.Column("clicks", sa.Integer(), nullable=False))
    op.add_column("metric_snapshots", sa.Column("impressions", sa.Integer(), nullable=False))
    op.add_column("metric_snapshots", sa.Column("spend", sa.Integer(), nullable=False))
    op.add_column("metric_snapshots", sa.Column("leads", sa.Integer(), nullable=False))
    op.add_column("metric_snapshots", sa.Column("purchases", sa.Integer(), nullable=False))
    op.add_column("metric_snapshots", sa.Column("revenue", sa.Integer(), nullable=False))
    op.add_column("metric_snapshots", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.drop_constraint("metric_snapshots_creative_variant_id_fkey", "metric_snapshots", type_="foreignkey")
    op.drop_constraint("metric_snapshots_experiment_id_fkey", "metric_snapshots", type_="foreignkey")
    op.drop_column("metric_snapshots", "experiment_id")
    op.drop_column("metric_snapshots", "creative_variant_id")
    op.drop_column("metric_snapshots", "collected_at")
    op.drop_column("metric_snapshots", "metrics_json")

    op.add_column("projects", sa.Column("advertiser_id", sa.Integer(), nullable=True))
    op.alter_column(
        "projects",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_foreign_key(None, "projects", "advertisers", ["advertiser_id"], ["id"])
    op.drop_column("projects", "updated_at")
    op.drop_column("projects", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column(
        "projects",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "projects", type_="foreignkey")
    op.alter_column(
        "projects",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("projects", "advertiser_id")

    op.add_column(
        "metric_snapshots",
        sa.Column("metrics_json", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    )
    op.add_column(
        "metric_snapshots",
        sa.Column(
            "collected_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column("metric_snapshots", sa.Column("creative_variant_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column("metric_snapshots", sa.Column("experiment_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(
        "metric_snapshots_experiment_id_fkey",
        "metric_snapshots",
        "experiments",
        ["experiment_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "metric_snapshots_creative_variant_id_fkey",
        "metric_snapshots",
        "creative_variants",
        ["creative_variant_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("metric_snapshots", "created_at")
    op.drop_column("metric_snapshots", "revenue")
    op.drop_column("metric_snapshots", "purchases")
    op.drop_column("metric_snapshots", "leads")
    op.drop_column("metric_snapshots", "spend")
    op.drop_column("metric_snapshots", "impressions")
    op.drop_column("metric_snapshots", "clicks")
    op.drop_column("metric_snapshots", "campaign_external_id")
    op.drop_column("metric_snapshots", "platform")
    op.drop_column("metric_snapshots", "date")

    op.add_column("hypotheses", sa.Column("assumptions_json", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column("hypotheses", sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column("hypotheses", sa.Column("expected_impact", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column("hypotheses", sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column("hypotheses", sa.Column("metrics_json", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column(
        "hypotheses",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "hypotheses", type_="foreignkey")
    op.create_foreign_key(
        "hypotheses_experiment_round_id_fkey",
        "hypotheses",
        "experiment_rounds",
        ["experiment_round_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "hypotheses",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("hypotheses", "segmentation_params")
    op.drop_column("hypotheses", "text")

    op.add_column("experiments", sa.Column("settings_json", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column("experiments", sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column(
        "experiments",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "experiments", type_="foreignkey")
    op.drop_constraint(None, "experiments", type_="foreignkey")
    op.create_foreign_key("fk_experiments_project_id_projects", "experiments", "projects", ["project_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key("experiments_plan_id_fkey", "experiments", "campaign_plans", ["plan_id"], ["id"], ondelete="CASCADE")
    op.alter_column(
        "experiments",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("experiments", "plan_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("experiments", "ended_at")
    op.drop_column("experiments", "started_at")
    op.drop_column("experiments", "end_at")
    op.drop_column("experiments", "start_at")
    op.drop_column("experiments", "processing")
    op.drop_column("experiments", "platforms")
    op.drop_column("experiments", "total_budget")

    op.add_column("experiment_rounds", sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column("experiment_rounds", sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column(
        "experiment_rounds",
        sa.Column(
            "status",
            postgresql.ENUM("planned", "running", "paused", "completed", name="experiment_round_status_enum"),
            server_default=sa.text("'planned'::experiment_round_status_enum"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column("experiment_rounds", sa.Column("metrics_json", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column("experiment_rounds", sa.Column("start_date", sa.DATE(), autoincrement=False, nullable=True))
    op.add_column(
        "experiment_rounds",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column("experiment_rounds", sa.Column("end_date", sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, "experiment_rounds", type_="foreignkey")
    op.create_foreign_key(
        "experiment_rounds_experiment_id_fkey",
        "experiment_rounds",
        "experiments",
        ["experiment_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_round_index", "experiment_rounds", type_="unique")
    op.alter_column(
        "experiment_rounds",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("experiment_rounds", "ended_at")
    op.drop_column("experiment_rounds", "started_at")
    op.drop_column("experiment_rounds", "budget_plan")
    op.drop_column("experiment_rounds", "round_index")

    op.add_column("creative_variants", sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column("creative_variants", sa.Column("external_creative_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column(
        "creative_variants",
        sa.Column(
            "status",
            postgresql.ENUM("draft", "approved", "rejected", "active", "paused", name="creative_status_enum"),
            server_default=sa.text("'draft'::creative_status_enum"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column("creative_variants", sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column(
        "creative_variants",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column("creative_variants", sa.Column("experiment_round_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, "creative_variants", type_="foreignkey")
    op.drop_constraint(None, "creative_variants", type_="foreignkey")
    op.create_foreign_key(
        "fk_creative_variants_hypothesis_id_hypotheses",
        "creative_variants",
        "hypotheses",
        ["hypothesis_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "creative_variants_experiment_id_fkey",
        "creative_variants",
        "experiments",
        ["experiment_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_creative_variants_experiment_round_id_experiment_rounds",
        "creative_variants",
        "experiment_rounds",
        ["experiment_round_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index("ix_creative_variants_compliance_token", "creative_variants", ["compliance_token"], unique=False)
    op.alter_column(
        "creative_variants",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "creative_variants",
        "compliance_token",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=64),
        existing_nullable=True,
    )
    op.drop_column("creative_variants", "external_ids")
    op.drop_column("creative_variants", "moderation_status")
    op.drop_column("creative_variants", "meta_json")
    op.drop_column("creative_variants", "media_url")
    op.drop_column("creative_variants", "image_url")
    op.drop_column("creative_variants", "title")
    op.drop_column("creative_variants", "text")
    op.drop_column("creative_variants", "platform")

    op.add_column("conversion_events", sa.Column("meta_json", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column(
        "conversion_events",
        sa.Column(
            "type",
            postgresql.ENUM("lead", "purchase", name="conversioneventtype"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "conversion_events", type_="foreignkey")
    op.drop_constraint(None, "conversion_events", type_="foreignkey")
    op.create_foreign_key("conversion_events_plan_id_fkey", "conversion_events", "campaign_plans", ["plan_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key("conversion_events_experiment_id_fkey", "conversion_events", "experiments", ["experiment_id"], ["id"], ondelete="SET NULL")
    op.drop_constraint(None, "conversion_events", type_="unique")
    op.alter_column(
        "conversion_events",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("conversion_events", "plan_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "conversion_events",
        "value",
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(precision=14, scale=2),
        existing_nullable=True,
    )
    op.drop_column("conversion_events", "contact_email")
    op.drop_column("conversion_events", "contact_phone")
    op.drop_column("conversion_events", "utm_term")
    op.drop_column("conversion_events", "utm_content")
    op.drop_column("conversion_events", "utm_campaign")
    op.drop_column("conversion_events", "utm_medium")
    op.drop_column("conversion_events", "utm_source")
    op.drop_column("conversion_events", "landing_url")
    op.drop_column("conversion_events", "occurred_at")
    op.drop_column("conversion_events", "event_type")
    op.drop_column("conversion_events", "event_id")

    op.add_column("connections", sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column(
        "connections",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "connections", type_="foreignkey")
    op.create_foreign_key("connections_advertiser_id_fkey", "connections", "advertisers", ["advertiser_id"], ["id"], ondelete="CASCADE")
    op.alter_column(
        "connections",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("connections", "advertiser_id", existing_type=sa.INTEGER(), nullable=False)

    op.drop_constraint(None, "campaign_plans", type_="foreignkey")
    op.create_foreign_key("campaign_plans_advertiser_id_fkey", "campaign_plans", "advertisers", ["advertiser_id"], ["id"], ondelete="CASCADE")

    op.add_column("budget_allocations", sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column("budget_allocations", sa.Column("plan_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column(
        "budget_allocations",
        sa.Column("allocated_budget", sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    )
    op.add_column(
        "budget_allocations",
        sa.Column("spent_budget", sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    )
    op.add_column("budget_allocations", sa.Column("date", sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "budget_allocations", type_="foreignkey")
    op.drop_constraint(None, "budget_allocations", type_="foreignkey")
    op.drop_constraint(None, "budget_allocations", type_="foreignkey")
    op.create_foreign_key(
        "budget_allocations_creative_variant_id_fkey",
        "budget_allocations",
        "creative_variants",
        ["creative_variant_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "budget_allocations_experiment_id_fkey",
        "budget_allocations",
        "experiments",
        ["experiment_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "budget_allocations_plan_id_fkey",
        "budget_allocations",
        "campaign_plans",
        ["plan_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        "uq_budget_allocations_plan_platform_date_creative",
        "budget_allocations",
        ["plan_id", "platform", "date", "creative_variant_id"],
    )
    op.alter_column(
        "budget_allocations",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("budget_allocations", "experiment_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("budget_allocations", "amount")
    op.drop_column("budget_allocations", "experiment_round_id")

    op.add_column(
        "advertisers",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "advertisers",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###
